import localFont from "next/font/local";
import "./globals.css"
import Header from "./_components/Header";
import FooterWrapper from "./_components/FotterWrabber";
import HeaderWrapper from "./_components/HeaderWrabber";
import Context from "./dashpoard/Context";
import Middleware from "./dashpoard/Middleware";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "RealEstate website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-medium `}
      >
        <>
        <Middleware>
          <Context>
              <HeaderWrapper />
        <main className="w-full min-h-screen">{children}</main>
        <FooterWrapper />
          </Context>
        </Middleware>
      
        </>
       
      </body>
    </html>
  );
}
